// <auto-generated />
using HotelHosting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelHosting.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    [Migration("20231018113752_SeededCountiresAndHotel")]
    partial class SeededCountiresAndHotel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HotelHosting.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "USA",
                            Name = "America"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "JP",
                            Name = "Japan"
                        });
                });

            modelBuilder.Entity("HotelHosting.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Anantapur",
                            CountryId = 1,
                            HotelName = "Masineni Hotel",
                            Rating = 2.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bangalore",
                            CountryId = 1,
                            HotelName = "Meghana Foods",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "New Jersey",
                            CountryId = 2,
                            HotelName = "Burger King",
                            Rating = 3.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kong Street",
                            CountryId = 3,
                            HotelName = "Noodles Hotel",
                            Rating = 3.2000000000000002
                        },
                        new
                        {
                            Id = 5,
                            Address = "Church Street",
                            CountryId = 2,
                            HotelName = "KFC",
                            Rating = 1.0
                        });
                });

            modelBuilder.Entity("HotelHosting.Data.Hotel", b =>
                {
                    b.HasOne("HotelHosting.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelHosting.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
